"""add hashed_password to usuarios

Revision ID: 8957c8e5d3ab
Revises: 001_initial
Create Date: 2026-04-23 22:07:49.173902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8957c8e5d3ab'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('proyectos')
    op.drop_table('tareas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=500), nullable=True),
    sa.Column('prioridad', sa.VARCHAR(length=5), server_default=sa.text("'MEDIA'"), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=11), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('proyecto_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=500), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
